---
apiVersion: v1
kind: Service
metadata:
  name: hamster-frontend
spec:
  selector:
    app: hamster-frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30301
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hamster-frontend
  labels:
    app: hamster-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hamster-frontend
  template:
    metadata:
      labels:
        app: hamster-frontend
    spec:
      containers:
        - name: hamster-frontend
          image: hamstershare/hamster-frontend:11071453
          imagePullPolicy: Always
          ports:
            - containerPort: 80
